# Generated by Django 3.2.8 on 2021-11-24 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_auto_20211109_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='hora',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='agendamento',
            field=models.DateField(default=datetime.date.today, verbose_name='Agendamento Sugerido'),
        ),
    ]
