# Generated by Django 3.2.8 on 2021-11-26 23:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0003_auto_20211124_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='hora',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='Hora'),
        ),
    ]
